version: '3.5'

services:
#===================================================================
#===================================================================
  mongo-test:
    image: mongo:4.2.6
    container_name: mongo-test
    restart: always
    hostname: mongo
    volumes:
      - mongotest-data:/data/mongo_test
#===================================================================
#===================================================================

  mongo-express-mongo:
    image: mongo-express
    restart: always
    container_name: mongotestadmin
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
        - mongo-test
    ports:
      - "8061:8081"
#===================================================================
#===================================================================
  db-test:
    image: mongo:4.2.6
    container_name: db-test
    restart: always
    hostname: mongo
    volumes:
      - dbtest-data:/data/db_test
#===================================================================
#===================================================================

  mongo-express-db:
    image: mongo-express
    restart: always
    container_name: dbtestadmin
    environment:
        - ME_CONFIG_MONGODB_SERVER=mongo
        - ME_CONFIG_MONGODB_PORT=27017
        - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
        - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
        - ME_CONFIG_BASICAUTH_USERNAME=admin
        - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
        - db-test
    ports:
      - "8071:8081"
#===================================================================
#===================================================================

volumes:
  database:
  mongotest-data:
  dbtest-data:
